<a href="https://colab.research.google.com/github/Yovana-Palencia/Mineria-De-Datos/blob/main/miner_a_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Mineria de datos

##Primer parcial

###Introducción

####Conceptos

¿Qué es minería de datos?
Es una técnica asistida por computadora que se utiliza en los análisis para procesar y explorar grandes conjuntos de datos

####Ciencia de datos

¿Qué es ciencia de datos? Es el estudio de datos con el fin de extraer información significativa para empresas.

####Help and Documentation in IPython

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
#Otra forma de obtener ayuda es utilizando ?
len?

In [ ]:
#Ejemplo de ayuda en una lista
L=[1,2,3]
L.insert?

In [ ]:
L?

In [ ]:
#Ejemplo con una función
def square(a):
  """Return the square of a."""
  return a ** 2

In [ ]:
square?

In [ ]:
square??

In [ ]:
#La función help nos muestra la ayuda
help(square)

Help on function square in module __main__:

square(a)
    Return the square of a.



In [ ]:
L.insert

####Help on magic functions:?, %magic, and %Ismagic

In [ ]:
%timeit?

In [ ]:
%magic

In [ ]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%bqsql  %%capture  %%debug  %%file  %%html  %%javascript  %%j

####IPython and Shell Commands

In [ ]:
$ echo "hello world"

SyntaxError: invalid syntax (ipython-input-3926258238.py, line 1)

####Understanding data types in Python

In [ ]:
import numpy as np

In [ ]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4. , 2. , 3. ])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1,2,3,4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i,i + 3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
import numpy as np

In [ ]:
np.random.seed(0) #seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim)  # La propiedad ndim nos dice el número de dimesniones
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print(x2.dtype)  # dtype nos dice el tipo de datos

int64


In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]  # Colocamos el índice del elemento a extraer, en este caso el primer elemento tienen el ídice 0

np.int64(5)

In [ ]:
x1[4]

np.int64(7)

In [ ]:
x1[-1]  # Nos regresa el último elemento del ndarray

np.int64(9)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0]

np.int64(3)

In [ ]:
x2[0, 2]

np.int64(2)

In [ ]:
x2[0, 0] = 12  # Asignar un nuevo valor (12) al renglón 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

####Estadística básica

Media (Mean)

In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [ ]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


In [ ]:
mediana = np.median(data)

Varianza y Desviación Estándar

In [ ]:
varianza = np.var(data)
desviacion = np.std(data)

Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

Array Indexing: Accessing Single Elements

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

np.int64(5)

In [ ]:
x1[3]

np.int64(3)

In [ ]:
x1[-1]

np.int64(9)

In [ ]:
x1[-2]

np.int64(7)

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[0,2]

np.int64(2)

In [ ]:
x2[2,3]

np.int64(7)

In [ ]:
x2[-1,-1]=2

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  2]])

####Análisis Estadístico Básico con NumPy

Media (Mean)

In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado

In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

Mediana

In [ ]:
mediana = np.median(data)

Varianza y Desviación Estándar

In [ ]:
varianza = np.var(data)
desviacion = np.std(data)

Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

0.0024029618578246446 1.00901955868826


Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])

####Pandas

In [ ]:
import numpy as np

import pandas as pd

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])

In [ ]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
dates = pd.date_range("20130101", periods=6)

In [ ]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [ ]:
df

A         B         C         D
2013-01-01 -0.078165 -1.978150 -0.870523  0.572509
2013-01-02  1.179121  0.086059 -1.172656 -0.150089
2013-01-03  1.794009 -3.133743 -0.787930  0.608469
2013-01-04  1.098511 -2.637345  0.055171  0.922357
2013-01-05  1.119739  0.274229  1.480892  1.376628
2013-01-06 -0.462494 -0.432205  0.823397  2.226991

In [ ]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

In [ ]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
df.head()

A         B         C         D
2013-01-01 -0.078165 -1.978150 -0.870523  0.572509
2013-01-02  1.179121  0.086059 -1.172656 -0.150089
2013-01-03  1.794009 -3.133743 -0.787930  0.608469
2013-01-04  1.098511 -2.637345  0.055171  0.922357
2013-01-05  1.119739  0.274229  1.480892  1.376628

In [ ]:
df.tail(3)

A         B         C         D
2013-01-04  1.098511 -2.637345  0.055171  0.922357
2013-01-05  1.119739  0.274229  1.480892  1.376628
2013-01-06 -0.462494 -0.432205  0.823397  2.226991

In [ ]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.to_numpy()

array([[-0.07816454, -1.97814959, -0.87052297,  0.57250862],
       [ 1.17912079,  0.08605857, -1.17265596, -0.15008948],
       [ 1.79400859, -3.13374321, -0.78793045,  0.6084688 ],
       [ 1.09851071, -2.63734458,  0.05517144,  0.92235696],
       [ 1.1197393 ,  0.27422884,  1.48089201,  1.37662835],
       [-0.46249436, -0.43220529,  0.82339693,  2.22699091]])

In [ ]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.775120 -1.303526 -0.078608  0.926144
std    0.858426  1.467197  1.057427  0.809865
min   -0.462494 -3.133743 -1.172656 -0.150089
25%    0.216004 -2.472546 -0.849875  0.581499
50%    1.109125 -1.205177 -0.366380  0.765413
75%    1.164275 -0.043507  0.631341  1.263061
max    1.794009  0.274229  1.480892  2.226991

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-01 to 2013-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [ ]:
df["A"].describe()

count    6.000000
mean     0.775120
std      0.858426
min     -0.462494
25%      0.216004
50%      1.109125
75%      1.164275
max      1.794009
Name: A, dtype: float64

In [ ]:
df.rename(columns=["A":"edad"])

SyntaxError: invalid syntax (ipython-input-774890357.py, line 1)

In [ ]:
edad_df = pd.read_csv("/content/datos.txt")

In [ ]:
edad_df

19/01/2026 18:32:18  178920  22  Si  No Si.1
0   19/01/2026 18:32:23  182712  21  Si  No   Si
1   19/01/2026 18:32:25  180370  26  Si  Si   Si
2   19/01/2026 18:32:27  182570  21  Si  Si   Si
3   19/01/2026 18:32:28  177622  24  Si  No   Si
4   19/01/2026 18:32:29  175166  22  Si  Si   Si
5   19/01/2026 18:32:30  177573  22  Si  Si   Si
6   19/01/2026 18:32:35  178430  21  Si  Si   Si
7   19/01/2026 18:32:38  179169  23  Si  No   Si
8   19/01/2026 18:32:41  177263  22  Si  Si   Si
9   19/01/2026 18:32:48  179884  23  Si  No   Si
10  19/01/2026 18:32:48  183016  22  Si  No   Si
11  19/01/2026 18:32:50  179033  23  Si  Si   No
12  19/01/2026 18:32:54  178218  22  Si  No   Si
13  19/01/2026 18:32:55  178446  22  Si  Si   Si
14  19/01/2026 18:33:00  178166  22  Si  Si   No
15  19/01/2026 18:33:02  177406  22  Si  No   Si
16  19/01/2026 18:33:05  177192  22  Si  Si   Si
17  19/01/2026 18:33:08  182451  21  Si  No   Si
18  19/01/2026 18:33:08  171513  24  No  No   Si
19  19/01/2026 18:33:09  181619  21  Si  No   Si
20  19/01/2026 18:33:12  182298  23  Si  No   Si
21  19/01/2026 18:33:14  181419  24  No  No   Si
22  19/01/2026 18:33:32  177291  21  Si  Si   Si
23  19/01/2026 18:33:42  182085  22  Si  No   Si
24  19/01/2026 18:33:53  176453  22  Si  No   Si
25  19/01/2026 18:34:04  176263  24  Si  No   Si
26  19/01/2026 18:34:06  179997  21  Si  No   Si
27  19/01/2026 18:36:21  175842  23  Si  No   No
28  19/01/2026 20:19:21  179913  20  Si  No   Si
29  19/01/2026 20:19:48  177301  22  Si  Si   No
30  19/01/2026 20:20:06  183060  21  Si  No   Si
31  19/01/2026 20:20:08  177935  22  Si  Si   Si
32  19/01/2026 20:20:19  177700  20  Si  Si   Si
33  19/01/2026 20:20:26  178318  24  Si  Si   Si
34  19/01/2026 20:20:27  174653  24  Si  No   Si
35  19/01/2026 20:20:29  177139  21  Si  No   Si
36  19/01/2026 20:20:31  173479  25  Si  No   No
37  19/01/2026 20:20:39  175588  23  No  No   Si
38  19/01/2026 20:20:45  178774  23  Si  Si   Si
39  19/01/2026 20:20:45  175031  23  Si  No   No
40  19/01/2026 20:20:49  178396  21  Si  Si   Si
41  19/01/2026 20:20:49  172068  23  No  No   No
42  19/01/2026 20:20:50  174197  23  No  No   Si
43  19/01/2026 20:20:55  178584  22  Si  No   Si
44  19/01/2026 20:20:55  175329  24  Si  No   Si
45  19/01/2026 20:20:56  177685  22  Si  Si   Si
46  19/01/2026 20:20:57  178678  22  No  No   Si
47  19/01/2026 20:21:04  177143  22  Si  No   Si
48  19/01/2026 20:21:07  182318  26  Si  No   Si
49  19/01/2026 20:21:27  182377  20  Si  No   Si
50  19/01/2026 20:21:34  179419  22  Si  No   No
51  19/01/2026 20:21:35  181662  21  Si  No   Si
52  19/01/2026 20:21:38  181760  21  Si  No   Si
53  19/01/2026 20:22:06  177888  22  Si  No   Si
54  19/01/2026 20:22:15  176535  25  Si  No   Si
55  19/01/2026 20:22:29  179862  21  Si  No   Si
56  19/01/2026 20:22:32  178378  22  Si  No   Si
57  19/01/2026 20:22:50  177451  22  Si  No   Si
58  19/01/2026 20:23:15  179804  21  Si  No   Si